---
abstract: 'LDAP filter to SQL clause transformer'
author:
  - 'Tim Esselens <tim.esselens@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102344, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-LDAP-Filter-SQL
requires:
  Net::LDAP::Filter: 0
resources:
  homepage: http://github.com/blaze-x/net-ldap-filter-sql/tree
  repository: git://github.com/blaze-x/net-ldap-filter-sql.git
version: 0.01
x_authority: cpan:ESSELENS
